apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch-release
  namespace: langturbo
spec:
  interval: 1h # for drifting resources
  releaseName: meilisearch
  targetNamespace: langturbo
  chart:
    spec:
      #renovate: registryUrl=https://meilisearch.github.io/meilisearch-kubernetes
      chart: meilisearch
      version: 0.17.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: meilisearch
        namespace: flux-system
  # install:
  #   createNamespace: false
  #   remediation:
  #     retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  # values:
  #   image:
  #     tag: "v1.12.8"
  #   existingMasterKeySecret: linkwarden-secret
  #   persistence:
  #     enabled: true
  #     storageClass: "longhorn-default-sc"
  #     size: "5Gi"
  #   service:
  #     type: ClusterIP
  #     port: 7700
  #   podLabels:
  #     homelab.category: database
  #     homelab.realm: search