apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: langturbo
spec:
  interval: 10m
  chart:
    spec:
      chart: meilisearch
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: meilisearch
      interval: 1m