---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch-release
  namespace: langturbo
spec:
  chart:
    spec:
      chart: meilisearch
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: meilisearch-repo
      version: 0.17.0
  interval: 1m0s
