apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: langturbo
spec:
  chart:
    spec:
      chart: meilisearch
      version: 0.17.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: langturbo
        name: meilisearch-repo
  interval: 1h
  # driftDetection:
  #   mode: enabled
  values:
    command:
      - tini
      - --
      - /bin/meilisearch
      - --experimental-dumpless-upgrade
    environment:
      MEILI_ENV: development
      #MEILI_LOG_LEVEL: WARN
    # auth:
    #   existingMasterKeySecret: meilisearch
    persistence:
      enabled: true
      storageClass: oci-bv
      size: 50Gi