apiVersion: v1
kind: Secret
metadata:
    name: nextjs-secrets
    namespace: langturbo
type: Opaque
stringData:
    NEW_TEST_KEY: ENC[AES256_GCM,data:TCC19+AQmQ==,iv:QwzvXfptQZ9uIApAZzidOAbFCl4qBShmiXnEy3cTwzs=,tag:jWaV84+W+AQ0C+Nlu83NPw==,type:str]
    LOL_NEWER_KEY: ENC[AES256_GCM,data:lBkpC6nG,iv:z9HF7z1xQm+qKPo16WvNwuyR4DEHNLVPzTFjwHZpTqA=,tag:f+izVCJ3iAWtcTD8B8FNcw==,type:str]
sops:
    age:
        - recipient: age12hunq95y0t65c8ax4rf0v5uwy5pxnyce7detujv6gju2u4ueayeq9vnxhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SDB1NDhIUlJWUlBTY0k4
            TlpqYzJIM0o4OU9QZE5wMVNnN2J3NFFKZTNVCmZ4ZklaSzJ2dVE2NmJPa3dJN0Na
            dkhNTHMrekdzZUM2Y1l6YU5UYjhjS2MKLS0tIFVsUXhWU0pEK2ovV3FlVXhqVTVR
            TjZLVDY1aVNIbEx5KzNOTytvcVBOdGcK6ZWJJ+e6tgFQiZm2K06RwD+MSarvwLeg
            UxxzuacfFE+qTYuMXuKpZv4CxK7XLn1zKFA0+gwOK26czqbg8El2+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T16:52:09Z"
    mac: ENC[AES256_GCM,data:g9GNwZb+Ws1eTnL5F1N+sxo9/vRaLXFuT/jXg7xWN8nFTV3WVtNYgOG/sZJY4tz1H27rQoNui9p1+vBlA0XSAK7NFzlctSy96/G8O/uYr7qlePBqNPKSHJqPwC2w8S/Li/B5p7qdMeyX2vR4/uNEQjl3A5qLBxs68dB5R8zHkMo=,iv:mhDk0553I15nVEs+MRyCkMh9B4041ekvGTwCd5xPPVc=,tag:L1/SqpBbxq3fJk5IFV5Elw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
