apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: nextjs-pod
  template:
    metadata:
      labels:
        pod: nextjs-pod
    spec:
      containers:
      - name: nextjs-container
        image: docker.io/sebnun/langturbo-nextjs:3