apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: langturbo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-container
        image: docker.io/sebnun/langturbo-nextjs:3
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-svc
  namespace: langturbo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: nextjs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  namespace: langturbo
  # annotations:
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  #   cert-manager.io/cluster-issuer: letsencrypt-prod
  #   nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - nextjs.domain.cloud
  #     secretName: prod-nextjs-tls-secret
  rules:
    - host: prev.langturbo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-svc
                port:
                  number: 80