
"""bot - Pipecat Voice Agent.

This bot uses a realtime pipeline: Speech-to-Speech with integrated LLM

Generated by Pipecat CLI

Required AI services:
- Gemini_Vertex_Live (Realtime Speech-to-Speech)

Run the bot using::
    uv run bot.py --transport daily
"""


from pipecat.services.google.gemini_live.llm_vertex import GeminiLiveVertexLLMService
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.transports.daily.transport import DailyTransport, DailyParams
from pipecat.runner.types import RunnerArguments
from loguru import logger
from pipecat.transports.base_transport import BaseTransport
from pipecat.pipeline.pipeline import Pipeline
import os
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor
from pipecat.pipeline.runner import PipelineRunner
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from dotenv import load_dotenv
from pipecat.runner.types import DailyRunnerArguments
import base64



load_dotenv(override=True)




async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Realtime LLM service (handles STT, LLM, and TTS internally)
    llm = GeminiLiveVertexLLMService(
            credentials=base64.b64decode(os.getenv("GOOGLE_APPLICATION_CREDENTIALS")),
            project_id=os.getenv("GOOGLE_PROJECT_ID"),
            location=os.getenv("GOOGLE_LOCATION"),
            voice_id=os.getenv("GOOGLE_VOICE_ID"),
            system_instruction=os.getenv("GOOGLE_SYSTEM_INSTRUCTION"),
    )



    messages = [
        {
            "role": "system",
            "content": "You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
        },
    ]

    context = LLMContext(messages)
    context_aggregator = LLMContextAggregatorPair(context)


    

    rtvi = RTVIProcessor()


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        rtvi,

        context_aggregator.user(),

        
        llm,

        
        transport.output(),

        
        
        context_aggregator.assistant(),

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
        ],
    )

    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        await rtvi.set_bot_ready()
        # Kick off the conversation
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    vad_analyzer=SileroVADAnalyzer(),
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()